version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: illuminate/log
    versions:
    - 8.29.0
    - 8.32.1
    - 8.33.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.39.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.3
